- name: install haproxy
  package:
    name: "{{ haproxy_packages }}"
    state: installed

- name: install haproxy configuration
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy

- name: activate haproxy
  service:
    name: haproxy
    state: started
    enabled: true
