- name: install keepalived
  package:
    name: "{{ keepalived_packages }}"
    state: installed

- name: configure sysctl
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: '1'
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/ip_nonlocal_bind.conf

- name: install keepalived configuration
  template:
    src: keepalived.conf
    dest: /etc/keepalived/keepalived.conf
  notify:
    - restart keepalived

- name: activate keepalived
  service:
    name: keepalived
    state: started
    enabled: true
